// GENERATED by _Kit\sync-kit.ps1 - do not edit by hand.
// Re-run:  .\sync-kit.ps1 -Project Project
//
// Lists only the namespaces this project owns. Adding a namespace means
// adding the folder under i18n\ and re-running the sync.

import faProject from '@/i18n/project/fa.json';
import enProject from '@/i18n/project/en.json';

export const DOMAIN_NAMESPACES = {
  fa: {
  'project': faProject,
  },
  en: {
  'project': enProject,
  },
} as const;
